spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5438/testdb-for-kotlin-course
    driver-class-name: org.postgresql.Driver
    username: alex
    password: secret
  liquibase:
    enabled: true
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: 'none'
    show-sql: true
    # fix for the postgres db issue - not implemented method
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - info
          - beans
  endpoint:
    beans:
      enabled: true
    info:
      enabled: true
  info:
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

crypto:
  secret: ${CRYPTO_SECRET}
  algorithm: ${CRYPTO_ALGORITHM}
  transformation: ${CRYPTO_TRANSFORMATION}


####### example multiple profiles #######

####### 'default' profile #######
#spring:
#  config:
#    activate:
#      on-profile:
#        - default
#  application:
#    name: course-catalog-service
#  datasource:
#    url: jdbc:postgresql://localhost:5438/testdb-for-kotlin-course
#    driver-class-name: org.postgresql.Driver
#    username: alex
#    password: secret
#  liquibase:
#    enabled: true
#  jpa:
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
#    hibernate:
#      ddl-auto: 'none'
#    show-sql: true
#    # fix for the postgres db issue - not implemented method
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#
#management:
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include:
#          - info
#          - beans
#  endpoint:
#    beans:
#      enabled: true
#    info:
#      enabled: true
#  info:
#    build:
#      enabled: true
#    java:
#      enabled: true
#    os:
#      enabled: true

---
####### 'dev' profile #######
#spring:
#  config:
#    activate:
#      on-profile:
#        - dev
#  datasource:
#    url: jdbc:h2:mem:testdb-for-kotlin-course
#    driver-class-name: org.h2.Driver
#    username: alex
#    password: secret
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2
#
#management:
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include:
#          - beans
#          - health
#          - info
#  endpoint:
#    beans:
#      enabled: true
#    health:
#      enabled: true
#    info:
#      enabled: true
#  info:
#    build:
#      enabled: true
#    java:
#      enabled: true
#    os:
#      enabled: true

---
####### 'test' profile #######
#spring:
#  config:
#    activate:
#      on-profile:
#        - test
#  datasource:
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
#    generate-ddl: true
#    show-sql: true
#
#management:
#  endpoints:
#    enabled-by-default: false