spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5438/testdb-for-kotlin-course
    driver-class-name: org.postgresql.Driver
    username: alex
    password: secret
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    hibernate:
      ddl-auto: 'update'
    show-sql: true
    # fix for the postgres db issue - not implemented method
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2

# default profile message
message: hallo from default profile
