spring:
  datasource:
    url: jdbc:h2:mem:testdb-for-kotlin-course
    driver-class-name: org.h2.Driver
    username: alex
    password: secret
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - beans
          - health
          - info
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  info:
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
