FROM openjdk:17-alpine
LABEL maintainer="AlMLand"
EXPOSE 8080
COPY course-catalog-service-0.0.1-SNAPSHOT.jar course-catalog-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar", "course-catalog-service-0.0.1-SNAPSHOT.jar"]